# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  boxes = [    
#    { :name => "mac", :box => "yzgyyang/macOS-10.14" }
#    { :name => "osx-box", :box => "ashiq/osx-10.14" },
    { :name => "mac_box", :box => "AndrewDryga/vagrant-box-osx" },
    { :name => "ubuntu_box", :box => "ubuntu/trusty64" }
#    { :name => "osx-box", :box => "jhcook/osx-elcapitan-10.11" }
  ]
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|      
      config.vm.box = opts[:box]
      
      if opts[:name] == boxes.last[:name]
        config.vm.provision "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.limit = "all"
          ansible.playbook = "test.yml"
        end
      end
    end
  end
end
