# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true

  boxes = [    
    { :name => "mac_box", :box => "ashiq/osx-10.14" },
    { :name => "ubuntu_box", :box => "ubuntu/bionic64" }
  ]
  ### Alternative mac boxes:
  # ramsey/macos-catalina # AndrewDryga/vagrant-box-osx # jhcook/osx-elcapitan-10.11
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|      
      config.vm.box = opts[:box]
      
      if opts[:name] == boxes.last[:name]
        config.vm.provision "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.limit = "all"
          ansible.playbook = "test.yml"
        end
      end
    end
  end
end
