---
### tasks file for djole_dev
- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- import_tasks: macos.yml
  when: ansible_distribution == 'MacOSX'
  
- name: Change current user shell
  user: shell=/bin/zsh name="{{ ansible_ssh_user }}"
  become: yes
- name: Check if oh-my-zsh is installed
  stat: path=~/.oh-my-zsh
  register: oh_my_zsh
- name: install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    version: master
    dest: ~/.oh-my-zsh
    update: False
  when: oh_my_zsh.stat.exists == False
