---
# tasks file for djole_dev
- debug:
    msg: Starting tasks >>>
- name: Install libraries using APT
  apt: name={{ item }} state=latest
  become: yes
  with_items:
    - zsh
- name: Change shell to ZSH
  user: shell=/bin/zsh name={{ ansible_ssh_user }}
